# Generated by Django 6.0.4 on 2026-04-21 16:10

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', tinymce.models.HTMLField(verbose_name='Açıklama')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(max_length=100, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('image', models.ImageField(upload_to='page_images/', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='isim')),
                ('content', tinymce.models.HTMLField(verbose_name='Açıklama')),
                ('content2', tinymce.models.HTMLField(verbose_name='Açıklama-2')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(max_length=100, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta Description')),
                ('miktar', models.IntegerField(verbose_name='Adet')),
                ('stok', models.BooleanField(default=True, verbose_name='Stok Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Kategori Resmi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Resim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.product')),
            ],
            options={
                'verbose_name': 'Ürün Resmi',
                'verbose_name_plural': 'Ürün Resimleri',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.productcategory'),
        ),
    ]
