# Generated by Django 6.0.4 on 2026-04-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Product_Category',
        ),
    ]
