# Generated by Django 6.0.4 on 2026-04-21 20:59

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_category_alter_product_image_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', tinymce.models.HTMLField(verbose_name='Açıklama')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(max_length=100, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='page_images/', verbose_name='Resim')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.about_page', verbose_name='Sayfa')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
