# Generated by Django 6.0.4 on 2026-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_about_page_page_image_delete_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='template_name',
            field=models.CharField(choices=[('category/default.html', 'Varsayılan Sayfa'), ('category/sports.html', 'Spor Sayfası'), ('category/local.html', 'Yerel Haber Sayfası'), ('category/economy.html', 'Ekonomi Sayfası')], default='category/default.html', help_text='Bu sayfa için kullanılacak şablonu seçin.', max_length=100, verbose_name='Şablon Adı'),
        ),
    ]
