# Generated by Django 6.0.4 on 2026-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_about_page_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_image',
            options={'verbose_name': 'Sayfa Resmi', 'verbose_name_plural': 'Sayfa Resimleri'},
        ),
        migrations.RemoveField(
            model_name='about_page',
            name='template_name',
        ),
        migrations.AlterField(
            model_name='page_image',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.about_page'),
        ),
    ]
